import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/options'
import prisma from '@/prisma/client'

export async function GET() {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const rooms = await prisma.discussionRoom.findMany({
      include: {
        createdBy: {
          select: {
            id: true,
            username: true,
            firstName: true,
            image: true
          }
        },
        participants: {
          select: {
            id: true,
            username: true,
            firstName: true,
            image: true
          }
        },
        _count: {
          select: {
            messages: true
          }
        }
      },
      orderBy: {
        updatedAt: 'desc'
      }
    })

    return NextResponse.json(rooms)
  } catch (error) {
    console.error('Error fetching rooms:', error)
    return NextResponse.json(
      { error: 'Failed to fetch rooms' },
      { status: 500 }
    )
  }
}

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user || !session.sub) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const json = await request.json()
    const { title } = json

    if (!title?.trim()) {
      return NextResponse.json(
        { error: 'Title is required' },
        { status: 400 }
      )
    }

    const room = await prisma.discussionRoom.create({
      data: {
        title: title.trim(),
        creatorId: session.user.id,
        participants: {
          connect: { id: session.user.id }
        },
        // Ensure these fields are handled correctly
        id: undefined, // Assuming id is auto-generated by Prisma
        updatedAt: new Date() // Set updatedAt to the current date
      },
      include: {
        createdBy: {
          select: {
            id: true,
            username: true,
            firstName: true,
            image: true
          }
        },
        participants: {
          select: {
            id: true,
            username: true,
            firstName: true,
            image: true
          }
        }
      }
    })

    return NextResponse.json(room)
  } catch (error) {
    console.error('Error creating room:', error)
    return NextResponse.json(
      { error: 'Failed to create room' },
      { status: 500 }
    )
  }
}